bundler_args: --without development
language: ruby
env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"
rvm:
  - 2.0.0
  - 2.1
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-2
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: ruby-head
  fast_finish: true
script: bundle exec rspec
sudo: false